### ISSUE TITLE
Parse and convert moment dates

### ISSUE THREAD

**Issue by boogheta** [medialab/google-bookmarklets#11]
Dates provided in google search use moment.js or similar technology resulting in some dates such as "Il y a 4 jours", "3 weeks ago".
It would be nice to be able to parse these and revert to actual iso dates

Ideas towards this can be found here: https://stackoverflow.com/questions/16754882/moment-js-reverse-fromnow
But handling locales is going to be complex, we need to find how to download and include in the page both [moment.js](https://github.com/moment/moment/tree/develop/dist/locale) and the desired corresponding [locale](https://github.com/moment/moment/tree/develop/dist/locale) and to adapt the regexp (maybe just `(\d+)\s+(\w+)` could suffice)

@Yomguithereal any experience doing this?

**Comment by Yomguithereal** [comment]
There are some helpers to easily inject some libraries when using artoo that could help indeed. I guess the "real" numeric date is not hidden somewhere in the html itself or in RAM?

**Comment by boogheta** [comment]
Nope, of course the real date is not int the html, haven't looked for residual var in ram though but I think it's actually processed serverside before the page is rendered
