### ISSUE TITLE
description and date field empty

### ISSUE THREAD

**Issue by mbroedl** [medialab/google-bookmarklets#13]
Hej,
Thank you so much for this fabulous tool.  Unfortunately it seems that the date and the description column are empty. I tried a few different languages but that did not help. Maybe these CSS selectors are out of date?
Thanks in advance for looking at this!

**Comment by boogheta** [comment]
Hello there,
I just pushed a fix that should do the trick, although I only tested on google.fr, don't hesitate and reopen the issue with a link to the version you're using if that does not fix it.

**Comment by mbroedl** [comment]
Great, this has worked for both columns. Thanks a lot for this!! :)
