### ISSUE TITLE
Handle more search engines

### ISSUE THREAD

**Issue by boogheta** [medialab/google-bookmarklets#19]
- [x] DuckDuckGo
- [x] Baidu
- [x] Qwant
- [x] Bing
- [ ] Yahoo
- [ ] Ecosia
- [ ] Brave
- [ ] Yandex
- [ ] ...

**Comment by jpontoire** [comment]
We can't increase the number of results per page on Yahoo, Ecosia, Brave and Yandex. They only have 6-10 results per page which would be way too slow to scrape.
