### ISSUE TITLE
catch forbidden on some domains

### ISSUE THREAD

**Issue by RouxRC** [medialab/google-bookmarklets#4]

**Comment by boogheta** [comment]
well actually it doesn't look like there are real ways to do that.
@Yomguithereal Is there a way to not even catch but just know that a Content Security Policy error occured in a page? for instance to warn via an alert that injecting an artoo script via a bookmarklet failed on websites such as Github for instance (no real use here, mostly theoretical question)

**Comment by Yomguithereal** [comment]
That's a tough one. I am not sure the javascript context can get this level of information on a request failure because it would be a security issue. However if what you need is to bypass csp headers we already assessed that we need an extension or launching the browser with perilous flags.

**Comment by boogheta** [comment]
I wasn't asking about bypassing csp, I know it requires browser tuning. I'm simply pondering whether there is any way to just "know" elsewhere than in the console whenever a csp rule occur: some event triggered that could be raised or such
